services:
  postgres_review:
    image: postgres:16
    container_name: review-postgres
    restart: unless-stopped
    networks:
      - internal_net
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - review_pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./db/city.csv:/docker-entrypoint-initdb.d/city.csv
    ports:
      - "5433:5432"

  redis_review:
    image: redis:7
    restart: unless-stopped
    networks:
      - internal_net

  review-service:
    build: .
    container_name: review-service
    restart: unless-stopped
    networks:
      - shared_network
      - internal_net
    depends_on:
      - postgres
      - redis
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DB_SSLMODE: disable
      REDIS_ADDR: ${REDIS_ADDR}
      SERVICE_TOKEN: ${SERVICE_TOKEN}
    volumes:
      - review_uploads:/app/uploads
      - ./keys/public.pem:/app/keys/public.pem:ro
    ports:
      - "8081:8080"

volumes:
  review_pgdata:
  review_uploads:

networks:
  internal_net:
  shared_network:
    external: true